#!/bin/bash


#1
java Queryfilemaker << EOF
1
EOF

for ((i=1; i<=5; i++))
do
	echo "n = 1" >> searchitresults.txt
	java SearchAVL >> searchitresults.txt
	echo "n = 1" >> searchavlresults.txt
	java SearchAVL >> searchavlresults.txt
done
#5
java Queryfilemaker << EOF
5
EOF

for ((i=1; i<=5; i++))
do
	echo "n = 5" >> searchitresults.txt
	java SearchAVL >> searchitresults.txt
	echo "n = 5" >> searchavlresults.txt
	java SearchAVL >> searchavlresults.txt
done
#10
java Queryfilemaker << EOF
10
EOF

for ((i=1; i<=5; i++))
do
	echo "n = 10" >> searchitresults.txt
	java SearchAVL >> searchitresults.txt
	echo "n = 10" >> searchavlresults.txt
	java SearchAVL >> searchavlresults.txt
done
#25
java Queryfilemaker << EOF
25
EOF

for ((i=1; i<=5; i++))
do
	echo "n = 25" >> searchitresults.txt
	java SearchAVL >> searchitresults.txt
	echo "n = 25" >> searchavlresults.txt
	java SearchAVL >> searchavlresults.txt
done
#50
java Queryfilemaker << EOF
50
EOF

for ((i=1; i<=5; i++))
do
	echo "n = 50" >> searchitresults.txt
	java SearchAVL >> searchitresults.txt
	echo "n = 50" >> searchavlresults.txt
	java SearchAVL >> searchavlresults.txt
done
#100
java Queryfilemaker << EOF
100
EOF

for ((i=1; i<=5; i++))
do
	echo "n = 100" >> searchitresults.txt
	java SearchAVL >> searchitresults.txt
	echo "n = 100" >> searchavlresults.txt
	java SearchAVL >> searchavlresults.txt
done
#250
java Queryfilemaker << EOF
250
EOF

for ((i=1; i<=5; i++))
do
	echo "n = 250" >> searchitresults.txt
	java SearchAVL >> searchitresults.txt
	echo "n = 250" >> searchavlresults.txt
	java SearchAVL >> searchavlresults.txt
done
#500
java Queryfilemaker << EOF
500
EOF

for ((i=1; i<=5; i++))
do
	echo "n = 500" >> searchitresults.txt
	java SearchAVL >> searchitresults.txt
	echo "n = 500" >> searchavlresults.txt
	java SearchAVL >> searchavlresults.txt
done
#1000
java Queryfilemaker << EOF
1000
EOF

for ((i=1; i<=5; i++))
do
	echo "n = 1000" >> searchitresults.txt
	java SearchAVL >> searchitresults.txt
	echo "n = 1000" >> searchavlresults.txt
	java SearchAVL >> searchavlresults.txt
done
#1500
java Queryfilemaker << EOF
1500
EOF

for ((i=1; i<=5; i++))
do
	echo "n = 1500" >> searchitresults.txt
	java SearchAVL >> searchitresults.txt
	echo "n = 1500" >> searchavlresults.txt
	java SearchAVL >> searchavlresults.txt
done
#2000
java Queryfilemaker << EOF
2000
EOF

for ((i=1; i<=5; i++))
do
	echo "n = 2000" >> searchitresults.txt
	java SearchAVL >> searchitresults.txt
	echo "n = 2000" >> searchavlresults.txt
	java SearchAVL >> searchavlresults.txt
done
#3000
java Queryfilemaker << EOF
3000
EOF

for ((i=1; i<=5; i++))
do
	echo "n = 3000" >> searchitresults.txt
	java SearchAVL >> searchitresults.txt
	echo "n = 3000" >> searchavlresults.txt
	java SearchAVL >> searchavlresults.txt
done
#4000
java Queryfilemaker << EOF
4000
EOF

for ((i=1; i<=5; i++))
do
	echo "n = 4000" >> searchitresults.txt
	java SearchAVL >> searchitresults.txt
	echo "n = 4000" >> searchavlresults.txt
	java SearchAVL >> searchavlresults.txt
done
#5000
java Queryfilemaker << EOF
5000
EOF

for ((i=1; i<=5; i++))
do
	echo "n = 5000" >> searchitresults.txt
	java SearchAVL >> searchitresults.txt
	echo "n = 5000" >> searchavlresults.txt
	java SearchAVL >> searchavlresults.txt
done
#5500
java Queryfilemaker << EOF
5500
EOF

for ((i=1; i<=5; i++))
do
	echo "n = 5500" >> searchitresults.txt
	java SearchAVL >> searchitresults.txt
	echo "n = 5500" >> searchavlresults.txt
	java SearchAVL >> searchavlresults.txt
done
#6000
java Queryfilemaker << EOF
6000
EOF

for ((i=1; i<=5; i++))
do
	echo "n = 6000" >> searchitresults.txt
	java SearchAVL >> searchitresults.txt
	echo "n = 6000" >> searchavlresults.txt
	java SearchAVL >> searchavlresults.txt
done
#7000
java Queryfilemaker << EOF
7000
EOF

for ((i=1; i<=5; i++))
do
	echo "n = 7000" >> searchitresults.txt
	java SearchAVL >> searchitresults.txt
	echo "n = 7000" >> searchavlresults.txt
	java SearchAVL >> searchavlresults.txt
done
#8000
java Queryfilemaker << EOF
8000
EOF

for ((i=1; i<=5; i++))
do
	echo "n = 8000" >> searchitresults.txt
	java SearchAVL >> searchitresults.txt
	echo "n = 8000" >> searchavlresults.txt
	java SearchAVL >> searchavlresults.txt
done
#9000
java Queryfilemaker << EOF
9000
EOF

for ((i=1; i<=5; i++))
do
	echo "n = 9000" >> searchitresults.txt
	java SearchAVL >> searchitresults.txt
	echo "n = 9000" >> searchavlresults.txt
	java SearchAVL >> searchavlresults.txt
done
#9500
java Queryfilemaker << EOF
9500
EOF

for ((i=1; i<=5; i++))
do
	echo "n = 9500" >> searchitresults.txt
	java SearchAVL >> searchitresults.txt
	echo "n = 9500" >> searchavlresults.txt
	java SearchAVL >> searchavlresults.txt
done
#10000
java Queryfilemaker << EOF
10000
EOF

for ((i=1; i<=5; i++))
do
	echo "n = 10000" >> searchitresults.txt
	java SearchAVL >> searchitresults.txt
	echo "n = 10000" >> searchavlresults.txt
	java SearchAVL >> searchavlresults.txt
done
